# Generated by Django 3.0.4 on 2020-03-30 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_auto_20200328_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='categora',
            new_name='categoria',
        ),
    ]
